# Generated by Django 5.2.2 on 2025-06-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('parameter', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('region', 'parameter', 'year', 'month')},
            },
        ),
    ]
